
// This file has been generated by the GUI designer. Do not modify.
namespace AstrogearsGUI
{
	public partial class RunButton
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AstrogearsGUI.RunButton
			global::Stetic.BinContainer.Attach (this);
			this.Name = "AstrogearsGUI.RunButton";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
